### ISSUE TITLE
`omod` and `omodi`

### ISSUE THREAD

**Issue by blipk** [mstuttgart/vscode-odoo-snippets#12]
The readme says "help you to develop Odoo modules faster and with no Typing Errors" however if I try to use this on a blank project folder the `omod` and associated snippets generate a class with the name `model.technical.name`:

```Python3
class model.technical.name(models.Model):
    _inherit = 'model.technical.name'


class model.technical.name(models.Model):
    _name = 'model.technical.name'
    _description = 'model.technical.name'


class TestModuleName(models.TransactionCase):

    def setUp(self):
        super(TestModuleName, self).setUp()
```

This is invalid python code and is also hard to select the name (can't double click) to change it to something valid.

Wouldn't `ModelTechnicalName` be better?

**Comment by mstuttgart** [comment]
@blipk hi! It is not a bug. You need to press 'tab' and insert the name of Model. After this, the extension it format the text to you.

**Comment by blipk** [comment]
Okay, I've noticed you've placed the cursor and if I press `ctrl + backspace` it deletes the whole line.

But that also leaves the tripple-cursor on all three lines, which isn't useful as the class name is different to the odoo dot notation for module.class access.

I can see in your GIF you get it auto-formatted to both formats though by typing the class name in dot notation, what key combination is that? 

![image](https://user-images.githubusercontent.com/45532845/224575554-7ad0b562-ae60-4b08-87bd-635b0c585cdb.png)

I still might prefer double clicking to select and editing the class name and _name seperately

**Comment by mstuttgart** [comment]
> I can see in your GIF you get it auto-formatted to both formats though by typing the class name in dot notation, what key combination is that?

I use 'TAB' key to navigate on cursors. After jumping to the cursor in `model.Models`, the extension auto-format to me. It's simple :)

**Comment by blipk** [comment]
Ah okay, I see how that works now thanks.

It'd still be nice if I could type the class name as `AccountInvoice` and still get the completion inferred the other way for the dot notation from the letter casing.

It feels wrong typing dot notation into the class name...

**Comment by mstuttgart** [comment]
> Ah okay, I see how that works now thanks, first time using snippets.

@blipk nice! 

> It'd still be nice if I could type the class name as `AccountInvoice` and still get the completion inferred the other way for the dot notation from the letter casing.

unfortunately, it is a limitation of snippet tool completion of vscode. I have tried to reproduce this behavior, but have not been successful.

> It feels wrong typing dot notation into the class name...

Yes, I understand you, but the autocomplete fixes the class name and works 😄  I need to document this better in the future 🤔 

Thanks for trying my extension!

**Comment by blipk** [comment]
Thanks, the vscode extension api did seem quite limiting from what I looked at.

This extension had the most consistent snippet naming from what I could see on the marketplace, maybe they expand the api at some point
